### ISSUE TITLE
does this one work?

### ISSUE THREAD

**Issue by jovo** [openconnectome/ndio-demos#1]
http://app.mybinder.org/2805214324/notebooks/kasthuri-statistics/Count%20Vesicles.ipynb

i got nuthin

**Comment by j6k4m8** [comment]
hm. i think mybinder switches up our links periodically... where was this link from?

**Comment by j6k4m8** [comment]
confirmed that the permalinks change.

**Comment by jovo** [comment]
well, its this one: kasthuri-statistics/Count%20Vesicles.ipynb
